# This is a generated config. Do not mess with it unless you know what you are doing!

author:
  name: Joshua Quaintance
baseurl: /
collections:
  Catalogue:
    output: true
description: A Portal for ODPA
markdown: GFM
tagline: ODPA Portal
title: ODPA Portal
