markdown: GFM

title: ODPA Portal
tagline: 'ODPA Portal'
description: 'A Portal for ODPA'
baseurl: /

author:
    name: 'Joshua Quaintance'

include: ['_Catalogue']

collections:
    Catalogue:
        output: true
        permalink: /catalogue/:name
